#!/usr/bin/env bash

########################################################################
# Include this file in your bashrc file to get genesis console activated in your terminal
########################################################################

# Source common functions file
source $(dirname "${BASH_SOURCE[0]}")/Source/Common;

if [[ -f $(dirname "${BASH_SOURCE[0]}")/Config/Variables ]]; then
	source $(dirname "${BASH_SOURCE[0]}")/Config/Variables;
else
    printf "\nConfig/Variables file not found, creating file now";
    genesisConfigCreate;
    genesisEditConfig;
fi

# Source config variables
sourceFile 'Config/Variables';

# Source bsah functions
sourceFile 'Source/bash';

# Source local functions
sourceFile 'Source/Local';

# Source remote functions
sourceFile 'Source/Remote';