#!/usr/bin/env bash

function print() {
	printf "** $1\r\n";
}

function genesisHelp() {
	print "Welcome to Genesis Remote Bash
==================================
-- Commands Available --


help - shows this menu
edit - edit genesis in editor
dir - switch to genesis directory
status - show git status
save - commit and push to repo
config - edit configuration
update - pull changes from repo
point ?[branch] - point to a branch
branch
  * list - lists branches
  * create ?[branch] - create new branch
  * delete ?[branch] - delete branch

bash
  * edit - edit genesis bash
  * reload - reload genesis bash env

remote
  * login - login to remote ssh server
  * update - update remote repo
  * point ?{branch} - point to branch/version/tag
";
}

function genesis() {
	case $1 in
		"help" )
			genesisHelp;;
		"edit" )
			genesisEdit;;
		"dir" )
			cd $genesis_dir;;
		"status" )
			genesisStatus;;
		"save" )
			genesisSave;;
		"update" )
			genesisUpdate;;
		"bash" )
			case $2 in
				"reload" )
					genesisBashReload;;
				"edit" )
					genesisBashEdit;;
			esac;;
		"config" )
			editGenesisConfig;;
		"*" )
			print "Unknown option entered, aborting";
	esac
}

function sourceFile() {
	source $genesis_vc$1;
}

function genesisConfigCreate() {
	cp $genesis_vc/Config/Variables $genesis_vc/Config/Variables.dist;
}