#!/usr/bin/env bash

function print() {
	printf "** $1\r\n";
}

function genesisHelp() {
	print "Welcome to Genesis Remote Bash

genesis
* help
* edit
* dir
* save";
}

function genesis() {
	case $1 in
		"help" )
			genesisHelp;;
		"edit" )
			genesisEdit;;
		"dir" )
			cd $genesis_dir;;
		"save" )
			genesisSave;;
		"reload" )
			genesisBashReload;;
	esac
}

function sourceFile() {
	source $genesis_vc$1;
}

function genesisConfigCreate() {
	cp $genesis_vc/Config/Variables $genesis_vc/Config/Variables.dist;
}