#!/usr/bin/env bash

function genesisEdit() {
	$genesis_editor $genesis_dir;
}

function genesisSave() {

	currentDir=$(pwd);
	cd $genesis_dir;

	if [[ ! -z $genesis_phpunitBin ]]; then

		print "Running PHPUnit, config search in: '$genesis_phpunitConfigPath'";
		# Run unit tests on app
		$genesis_phpunitBin -c $genesis_phpunitConfigPath;

		print "Are you sure you want to save data after considering the output above? [Y/N]";
		if [[ $(userChoice) != 'Y' ]]; then
			print "Aborting";
			cd $currentDir;
			return;
		fi
	fi

	if [[ -z $(git diff --name-only) ]]; then
		print "No file changes found, Attempting to push commits/tags";
		genesisPush;
		genesisPushTag;
		
		return;
	fi

	print "Files edited:";
	git diff --name-only

	cd $currentDir;

	print "Please enter a commit message:";
	read message;

	cd $genesis_dir;

	genesisTags;
	genesisVersion;

	cd $currentDir;

	print "Please enter a version number for this push: (leave empty to skip tagging)";
	read version;

	print "Attempting to commit with message '$message' and tag '$version', continue? [Y/N]";
	if [[ $(userChoice) != 'Y' ]]; then
		return;
	fi

	print "Saving changes with message: '$message'";

	cd $genesis_dir;

	genesisPush $message;

	if [[ ! -z $version ]]; then
		git tag $version;
		genesisPushTag $version;
	fi

	cd $currentDir;
}

function genesisPush() {
	cd $genesis_dir;

	git pull;
	git add --all;
	git commit -m "$1";
	git push;
}

function genesisPushTag() {
	cd $genesis_dir;
	git push --tag;
}

function genesisUpdate() {
	print "Updating genesis on local machine";
	currentDir=$(pwd);
	cd $genesis_dir;
	git pull;
	genesisBashReload;
	cd $currentDir;
}

function genesisStatus() {
	print "Showing git status on Genesis";
	currentDir=$(pwd);
	cd $genesis_dir;
	git status;
	cd $currentDir;
}

function genesisTags() {
	print "Existing Tags:";
	currentDir=$(pwd);
	cd $genesis_dir;
	git tag;
	cd $currentDir;
}

function genesisVersion() {
	print "Current version:";
	currentDir=$(pwd);
	cd $genesis_dir;
	version=$(git describe --tag);
	echo $version;

	if [[ $1 == '--more' ]]; then
		print "Info";
		git show $version;
	fi

	cd $currentDir;
}

function genesisPoint() {

	if [[ -z $1 ]]; then
		branch=$genesis_defaultBranch;
	else
		branch=$1;
	fi

	print "Pointing local env to branch/tag '$branch':";
	currentDir=$(pwd);
	cd $genesis_dir;
	git checkout $branch;
	cd $currentDir;
}

function genesisExecute() {
	print "Enter command to run:";
	read genesisCommand;

	if [[ -z $genesisCommand ]]; then
		return;
	fi

	currentDir=$(pwd);
	cd $genesis_dir;
	$genesisCommand;
	cd $currentDir;
}

function genesisBranch() {
	print "Showing branches:";
	currentDir=$(pwd);
	cd $genesis_dir;
	git branch;
	cd $currentDir;
}

function genesisBranchCreate() {
	print "Creating/Switching branch '$1':";
	currentDir=$(pwd);
	cd $genesis_dir;
	git branch $1;
	git checkout $1;
	git branch -u origin/$1;
	cd $currentDir;
}

function genesisBranchDelete() {
	print "Deleting branch '$1':";
	currentDir=$(pwd);
	cd $genesis_dir;

	if [[ ! -z $genesis_defaultBranch ]]; then
		git checkout $genesis_defaultBranch;
	fi
	
	git branch -D $1;
	cd $currentDir;
}

function genesisLog() {
	print "Showing log entries:";
	currentDir=$(pwd);
	cd $genesis_dir;

	if [[ -z $1 ]]; then
		git log -n 3;
	else
		git log -n $1;
	fi

	cd $currentDir;
}