#!/usr/bin/env bash

function genesisRemoteFetch() {
	genesisSSH "cd $genesis_remoteDir; git fetch;";
}

function genesisRemotePoint() {
	if [[ -z $1 ]]; then
		if [[ -z $genesis_defaultBranch ]]; then
			print "You must enter a branch/version/tag to point the server to";
			return;
		fi
		branch=$genesis_defaultBranch;
	else
		branch=$1;
	fi;

	print "Pointing remote server to branch/tag: $branch";
	genesisSSH "cd $genesis_remoteDir; git fetch; git checkout $branch";
}

function genesisSSH() {
	if [[ -z $genesis_sshUser ]] || [[ -z $genesis_sshIp ]]; then
		print "Unable to run remote command, please set config using command: 'genesis bash config'";
		return;
	fi

	ssh "$genesis_sshUser"@"$genesis_sshIp" "$1";
}

function genesisRemoteTags() {
	print "Showing tags on server:";
	genesisSSH "cd $genesis_remoteDir; git tag";
}

function genesisRemoteVersion() {
	print "Showing current version on server:";
	genesisSSH "cd $genesis_remoteDir; git describe --tags";
}

function genesisRemoteExecute() {
	print "Enter command to execute on remote server:";
	read genesisRemoteCommand;
	print "Executing '$genesisRemoteCommand' on remote server:";
	genesisSSH "$genesisRemoteCommand";
}